name: Update Chainlists

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions: write-all

jobs:
  update_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Update JSON file
        run: |
          bash .github/workflows/utility/update_lists.sh
          git config user.name workflow
          git config user.email workflow
          git commit --amend --reuse-message=HEAD
          git push --force
